name: Build & Pack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet pack --verbosity normal --configuration Release

    - name: Push
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet nuget push nuget/*.nupkg -s https://www.nuget.org/ -k ${{ secrets.nuget_api_key }}
